services:

  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./project:/code/project
    command: ./manage.py runserver 0.0.0.0:8000
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings