# Generated by Django 4.2.1 on 2023-06-01 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('data_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtrends.dataconfig')),
                ('ml_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtrends.mlconfig')),
            ],
        ),
        migrations.CreateModel(
            name='PreprocessingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('params', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(choices=[('GOOGLE_TRENDS', 'Google Trends')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TSVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(default=False)),
                ('timeseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtrends.timeseries')),
            ],
        ),
        migrations.CreateModel(
            name='TSValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtrends.tsversion')),
            ],
        ),
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ml_file', models.FileField(upload_to='ml_models')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField()),
                ('ml_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtrends.mlmodel')),
            ],
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='preprocess_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtrends.preprocessingconfig'),
        ),
        migrations.CreateModel(
            name='DataTargets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='gtrends.dataconfig')),
                ('timeseries', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtrends.timeseries')),
            ],
        ),
        migrations.CreateModel(
            name='DataFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='gtrends.dataconfig')),
                ('timeseries', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gtrends.timeseries')),
            ],
        ),
    ]
